package com.dvdev.jdbc.starter;

import com.dvdev.jdbc.starter.util.ConnectionManager;
import com.dvdev.jdbc.starter.util.ConnectionManagerForPool;
import org.postgresql.Driver;

import java.sql.SQLException;
import java.sql.Statement;

public class JdbcRunner {

    public static void main(String[] args) throws SQLException {
        Class<Driver> driverClass = Driver.class;
        String sql = """
                INSERT INTO info(data)
                VALUES
                ('autogenerated');
                """;

        try(var  connection = ConnectionManagerForPool.get();
            var statement = connection.createStatement()) {
            System.out.println(connection.getSchema()); //получаем дефолтную схему для соединения
            System.out.println(connection.getTransactionIsolation());

            var executeResult = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            var generatedKeys = statement.getGeneratedKeys(); //резалтсет айдишников
            if(generatedKeys.next()) {
                var generatedId = generatedKeys.getInt("id");
                System.out.println(generatedId);
            }
        }
    }
}
